### ISSUE TITLE
Update SCL Ecore model : attribute "value" missing in class "Private"

### ISSUE THREAD

**Issue by ADehouck** [riseclipse/riseclipse-metamodel-scl2003#1]
An update of the SCL ecore model is needed, in order to serialize the content of the <Private> element :
Currently, this value is not modelled in the ecore model (yyyy on the example bellow)
`    <Private type="xxxx">yyyy<Private>`
the same case occured for the <Val> element, and an attribute "value" has been added in order to store its content.

-> Add an attribute "value" to the class "Private"

**Comment by marcadetd** [comment]
The content of a Private element is stored by its superclass, AnyContentFromOtherNamespace.
In XSD, this complexType is mixed, so it can directly contain text, but also XML structured data.
This is why a simple String value, like the one in Val, is not enough.
The content of a Private element is accessed with OCL using the mixed attribute. For the given example, the result should be 'ecore.xml.type:text=yyyy'
However, a derived value attribute could be added to get only the 'yyyy' part. Is this needed ?

**Comment by Sketels-ar** [comment]
A derived value attribute to get only the 'yyyy' part  would be very useful.
Is this attribute would work if the the private tag contains some piece of XML from another namespace ?
By example:
		<Private type="xxxxx">
			**<esel:tag1>
				<esel:tag2 format="VB{0:D3}" min="1" max="128"/>
			</esel:tag1>**
		</Private>
The purpose is to store the content of the private tag as a string whatever its format is.
As well we need to generate same private tag with its content.

**Comment by marcadetd** [comment]
Fixed in pull request #7
