### ISSUE TITLE
Default Value for attributes

### ISSUE THREAD

**Issue by Sketels-ar** [riseclipse/riseclipse-metamodel-scl2003#2]
The Default Value for attribute bufMode in ConfReportControl should be 'both', while it is currently 'unbuffered'.
As well in some cases, when an attribute wich is not mandatory is not present in a file, RiseClipse generate an attribute with a default value anyway.
Exemple: 
The attribute owner in ReportSettings is not mandatory.
When RiseClipse read a file containing a ReportSettings whith no owner attribute, RiseClipse initializes the owner attribute in the class ReportSettings to false wich is the default value. 
Should RiseClipse not initialize the owner attribute at all ?

**Comment by marcadetd** [comment]
I understand "default value" as the value to give to the attribute if it is not present in the SCL file. Because, if it is present, it must have a value, even if it is the default one.
Therefore, what will be the benefit of having uninitialized attributes?

**Comment by Sketels-ar** [comment]
My problem is that if an attribute is not present in the SCL file i'm readind, i want to store the attribute to null
Right now i use methods isSet... wich check if an attribute or a field is present in the SCL file.
So if the method sends back false,  i don't use the get method.

**Comment by marcadetd** [comment]
Default value of bufMode is set to 'both' in current develop branch. According to my tests, isSetBufMode() returns false if bufMode is not present in the SCL file, and true if present with a value, including the default one. Can you check if it is OK for you ?

**Comment by marcadetd** [comment]
Fixed in pull request #7
