### ISSUE TITLE
Add an attribute to FCDA class, that stores the order number of a FCDA inside a DataSet 

### ISSUE THREAD

**Issue by ADehouck** [riseclipse/riseclipse-metamodel-scl2003#52]
The ordering of the FCDA elements inside a DataSet is important,

Could we add and attribute "ordNb" for example, that would contain an "integer" that represents the place of an FCDA inside a DataSet ?

![image](https://github.com/riseclipse/riseclipse-metamodel-scl2003/assets/62877587/a72f1612-7dab-4f01-88a1-0bdd1c98a9aa)

**Comment by marcadetd** [comment]
done in commit 67f5bb5
